FROM resin/%%RESIN_MACHINE_NAME%%-python

ARG tag=master

WORKDIR /usr/local/src
RUN git clone --branch $tag https://github.com/foosel/OctoPrint.git /usr/local/src \
  && virtualenv venv \
	&& ./venv/bin/python setup.py install

ENTRYPOINT /usr/local/src/venv/bin/octoprint serve --iknowwhatimdoing --host 0.0.0.0 --port 80 --basedir /data/octoprint
